server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_stock?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

seata:
  enabled: true
  application-id: stock-service
  tx-service-group: my_test_tx_group
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
  config:
    type: nacos
    nacos:
      serverAddr: localhost
      group: SEATA_GROUP
      namespace:
      userName: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      cluster: default
      server-addr: localhost
      namespace:
      userName: "nacos"
      password: "nacos"